### ISSUE TITLE
thinking about maximum region size

### ISSUE THREAD

**Issue by honggyukim** [awslabs/damo#70]
Hi SeongJae,

I've been testing paddr mode DAMON in a system, which has a large system memory so emulated the system in my qemu setting with 160GB of memory.

I have internally implemented promote actions, but found that it sometimes can't capture hot regions for a very long time. I have a simple program that creates 200MB of frequently accessed memory block but the action doesn't get triggered.

I have checked the status of regions, but it shows only 13 regions as follows and they show 0% access rate. The weird part was that they mostly show very young ages.
```
$ ./damo show
total number of regions: 13
  0 addr [4.000 KiB, 640.000 KiB) (636.000 KiB) access 0 % age 100 ms
  1 addr [1024.000 KiB, 3.000 GiB) (2.999 GiB) access 0 % age 100 ms
  2 addr [4.000 GiB, 19.579 GiB) (15.579 GiB) access 0 % age 200 ms
  3 addr [19.579 GiB, 35.272 GiB) (15.693 GiB) access 0 % age 400 ms
  4 addr [35.272 GiB, 50.906 GiB) (15.634 GiB) access 0 % age 300 ms
  5 addr [50.906 GiB, 66.601 GiB) (15.695 GiB) access 0 % age 200 ms
  6 addr [66.601 GiB, 82.237 GiB) (15.636 GiB) access 0 % age 500 ms
  7 addr [82.237 GiB, 97.809 GiB) (15.572 GiB) access 0 % age 500 ms
  8 addr [97.809 GiB, 113.378 GiB) (15.569 GiB) access 0 % age 500 ms
  9 addr [113.378 GiB, 128.978 GiB) (15.600 GiB) access 0 % age 500 ms
 10 addr [128.978 GiB, 144.558 GiB) (15.580 GiB) access 0 % age 400 ms
 11 addr [144.558 GiB, 160.256 GiB) (15.698 GiB) access 0 % age 400 ms
 12 addr [160.256 GiB, 161.000 GiB) (762.141 MiB) access 0 % age 400 ms
total sz: 160.000 GiB
```
The size of each region looks as 16GB and I feel it might be very difficult to randomly capture the accessed page among those regions.

So I think we may have to think about having a maximum size of region to prevent this case. There is no specific size limit as of now so the region size can grow too huge.

I would like to hear how you think about this.

**Comment by sj-aws** [comment]
Hi Honggyu,

Thank you for sharing the result.

DAMON actually have the maximum size of region.  It sets it by dividing the size of the total memory to monitor by the `min_nr_regions`.  You could set it using `--monitoring_nr_regions_range` option of `damo`.  So you could reduce the maximum size of each region by increasing the minimum number of monitoring regions.

**Comment by sj-aws** [comment]
FYI, DAMON can sometimes make access rate of regions larger than 100%, due to some timing errors.  And `damo` was assuming the maximum access rate would be 100%.  Hence, `damo show` was not showing regions having >100% access rate.  `damo schemes` was also having similar issue.  The issue has fixed with commit 3641ac72147f ("_damo_fmt_str: Make text_to_{ratio,permil,percent}() to return more than 100% for 'max'"), which merged in v1.9.0 of `damo`.  It's unclear if the issue made some effect to your case, but sharing for any possible case.

**Comment by honggyukim** [comment]
Hi SeongJae,

Sorry for the late response.

> DAMON actually have the maximum size of region. It sets it by dividing the size of the total memory to monitor by the min_nr_regions. You could set it using --monitoring_nr_regions_range option of damo. So you could reduce the maximum size of each region by increasing the minimum number of monitoring regions.

Yes, that what I'm currently doing. I've changed the minimum `nr_regions` to `100` for now. But I also saw that one of the region size was more than 100GB so I'm not sure if it's possible to detect memory accesses from any of the page from that huge region with sampling. I was thinking that we might have to consider the size limit of a region so that the region can't grow larger that the limit.

> FYI, DAMON can sometimes make access rate of regions larger than 100%, due to some timing errors. And damo was assuming the maximum access rate would be 100%. Hence, damo show was not showing regions having >100% access rate. damo schemes was also having similar issue. The issue has fixed with commit https://github.com/awslabs/damo/commit/3641ac72147f9f300a9f92798812e834b95e66e5 ("damo_fmt_str: Make text_to{ratio,permil,percent}() to return more than 100% for 'max'"), which merged in v1.9.0 of damo. It's unclear if the issue made some effect to your case, but sharing for any possible case.

I didn't know that. I have rebased onto the current `next` branch. Thanks for letting me know.

**Comment by honggyukim** [comment]
> DAMON actually have the maximum size of region. It sets it by dividing the size of the total memory to monitor by the min_nr_regions. You could set it using --monitoring_nr_regions_range option of damo. 

Hmm.. I have set the minimum `nr_regions` to `100`, but I still see only about less than `30` regions. Is the minimum nr_regions a soft limit that doesn't always have to be required?

**Comment by sj-aws** [comment]
Sorry for late reply, I somehow missed your final question.  It is not intended to be a soft limit, though it has a chance to work in that way under online tuning.  So I guess this maybe somewhat need to be fixed.  Could you please let me know how I can reproduce it?

**Comment by honggyukim** [comment]
Sorry for the late answer again. I remember there was a bug in our local change so I thought it as a soft limit. I will check again later if it still doesn't work. I'm currently focusing on many different items so I easily foget things to catch up. Sorry about that.

**Comment by sj-aws** [comment]
After 2024-09-05, we will[1] use damonitor repo[2] as the only main repo for GitHub.  To continue discussion of this issue on the repo, I just created a new issue[3] there.  Please use the new issue for followup discussions.

Closing this issue in favor of the new one on the damonitor repo. Please ask me to open this again if you cannot continue the discussion from the new issue.

[1] https://lore.kernel.org/20240813232158.83903-1-sj@kernel.org
[2] https://github.com/damonitor/damo
[3] https://github.com/damonitor/damo/issues/6
